# Generated by Django 4.1.3 on 2022-12-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsstory_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='news_image',
            field=models.URLField(blank=True),
        ),
    ]
