# Generated by Django 4.1.3 on 2022-12-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newsstory_modified_date_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='modified_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
