# Generated by Django 4.1.3 on 2022-12-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_newsstory_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
